'use client';

import React from 'react';
import { motion } from 'framer-motion';

interface DrawingStep {
  index: number;
  pathData: string; // The inner SVG content for this group
  instruction: string;
}

interface DrawingCanvasProps {
  steps: DrawingStep[];
  currentStepIndex: number;
  zoom?: number;
  isTarget?: boolean;
}

/**
 * DrawingCanvas component that renders SVG templates progressively.
 * Highlights the current step with a blue pulse animation.
 * 
 * @param {DrawingCanvasProps} props - Component props.
 * @returns {JSX.Element} The rendered drawing canvas.
 */
export const DrawingCanvas: React.FC<DrawingCanvasProps> = ({
  steps,
  currentStepIndex,
  zoom = 0.5,
  isTarget = false,
}) => {
  return (
    <div className={`flex-1 w-full flex items-center justify-center p-8 overflow-hidden relative ${isTarget ? 'bg-transparent' : 'bg-white'}`}>
      <svg
        viewBox="0 0 400 400" // Standard viewBox, should ideally come from template
        className="w-full h-full max-w-4xl transition-transform duration-300"
        style={{ 
          filter: 'drop-shadow(0px 4px 10px rgba(0,0,0,0.1))',
          transform: `scale(${zoom})`
        }}
      >
        {steps.map((step, idx) => {
          const actualIndex = step.index !== undefined ? step.index : idx;
          const isVisible = actualIndex <= currentStepIndex;
          const isLatest = actualIndex === currentStepIndex && !isTarget;

          // Some templates generated by subagents used different property names
          // @ts-ignore - allow fallback to svgPath or svg
          let innerHtml = step.pathData || step.svgPath || step.svg || '';

          // CRITICAL: If the step is not visible yet, strip any <style> tags so they don't leak globally!
          // CSS is applied to the DOM regardless of opacity: 0.
          if (!isVisible) {
            innerHtml = innerHtml.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, '');
          }

          return (
            <motion.g
              key={actualIndex}
              initial={{ opacity: 0 }}
              animate={{ 
                opacity: isVisible ? 1 : 0,
                scale: isLatest ? [1, 1.05, 1] : 1,
              }}
              transition={{
                opacity: { duration: 0.5 },
                scale: isLatest 
                  ? { 
                      duration: 2, 
                      repeat: Infinity, 
                      ease: "easeInOut" 
                    } 
                  : { duration: 0.2 }
              }}
              style={{
                stroke: isLatest ? '#0000FF' : '#333333', // Blue pulse for latest, dark gray for others
                strokeWidth: isLatest ? 2 : 1.5,
                fill: 'none',
                strokeLinecap: 'round',
                strokeLinejoin: 'round'
              }}
              dangerouslySetInnerHTML={{ __html: innerHtml }}
            />
          );
        })}
      </svg>
    </div>
  );
};
